### ISSUE TITLE
Clipboard.Clear() does not clear the clipboard.

### ISSUE THREAD

**Issue by mfeemster** [DanielVanNoord/System.Windows.Forms#17]
On linux, not sure about Windows, calling `Clipboard.Clear()` does not actually clear the clipboard.

```
Clipboard.SetDataObject("hello", true);
var val = Clipboard.GetData(DataFormats.Text) as string;
Console.WriteLine(val);//Prints hello.
Clipboard.Clear();
val = Clipboard.GetData(DataFormats.Text) as string;
Console.WriteLine(val);//Prints hello again, when it should be an empty string.
Clipboard.SetDataObject("", true);//Actually clears the clipboard.
val = Clipboard.GetData(DataFormats.Text) as string;
Console.WriteLine(val);//Properly prints nothing.
```

I've traced the call down to this code in `X11Clipboard.cs`:

```
internal void Clear () {
			XplatUIX11.XSetSelectionOwner (XplatUIX11.Display, Selection, IntPtr.Zero, UIntPtr.Zero);
}
```

There is some documentation on `XSetSelectionOwner ()` which says the time parameter (last one) must match the server time or else nothing is done. So that might be a place to start.

Note I am running with the latest refactored clipboard code.

**Comment by madewokherd** [comment]
Use of 0 (a special timestamp value symbolically named CurrentTime in the X11 headers) should work fine for this. Wine does the same thing.

My immediate suspicion is that this does successfully clear the clipboard from the perspective of other X11 programs, but there's some in-process caching that doesn't get cleared.

**Comment by madewokherd** [comment]
Yup, `X11Clipboard.GetContent` uses an `Outgoing` field to track clipboard contents from the current process: https://github.com/DanielVanNoord/System.Windows.Forms/blob/master/System.Windows.Forms/System.Windows.Forms/X11Clipboard.cs#L140

But `X11Clipboard.Clear` doesn't reset that field. While we do reset when we get a `SelectionClear` event (https://github.com/DanielVanNoord/System.Windows.Forms/blob/master/System.Windows.Forms/System.Windows.Forms/X11Selection.cs#L170), and we should get one in theory, those are delivered asynchronously - you'd need to process messages to actually get them. In this case, there's nothing processing messages between your `Clear` call and `GetData`.

I think it would make sense for `X11Clipboard.Clear` to call `X11Selection.HandleSelectionClearEvent` after setting the selection owner.

There are probably other issues with asynchronous SelectionClear. One scenario that occurs to me is Clear followed by SetDataObject. We'll end up getting the SelectionClear event from the Clear call after setting new data, which we'll then incorrectly discard. In theory, we should use the timestamp to determine whether the SelectionClear event happened before or after our most recent XSetSelectionOwner request, but we don't really have a way to get that timestamp when we're using CurrentTime. Apparently, Wine handles this by creating a new window every time it updates the clipboard.

**Comment by madewokherd** [comment]
Made an MR in Mono: https://gitlab.winehq.org/mono/mono/-/merge_requests/85

Will send a PR here once I've confirmed it doesn't break the tests.
