### ISSUE TITLE
Support for .NET 7+

### ISSUE THREAD

**Issue by mfeemster** [DanielVanNoord/System.Windows.Forms#6]
I found your project from an MS forum post and it is exactly what I need. However, I am having a few issues and wanted to get your input on the path forward.

I have a .NET 8 C# project running Windows that uses Winforms.
I need this same code to run on linux with minimal modifications.

The only platform that allows such is Mono. However, it's stuck in the .NET Framework era and appears to be a dead project. Therefore it won't compile my .NET 8 code that uses things like `SearchValues`.

So that led me here. However, I am seeing that you make use of System.Drawing.Common, which on linux relies heavily on libgdiplus. MS has now forcefully removed support for this. If you try to run it with any version of .NET after 6, it will throw an exception on program start, stating that it is not a cross platform library.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

This presents a problem because the Windows.Forms code makes heavy use of `System.Drawing.Graphics` objects.

Which way should I proceed to do this? The only way I see possible is to pull the System.Drawing.* code out of Mono and include it in this project. That way, this project would build its own copy of both System.Drawing and System.Windows.Forms from Mono.

Please let me know your thoughts because outside of this approach, I am fearing that my project (and any modern Winforms project) is doomed on linux.

Thanks.

**Comment by sancheolz** [comment]
The System.Drawing.Common is just nuget package and this implementation of WinForms strongly referenced to 6.0 version of package. You can target your project to net8.0 framework and add package reference to current Core.System.Windows.Forms and it will work. You just need to check direct refs to System.Drawing.Common in your project - they also must be 6.0 version. I've already checked my project for compatibility with .net 8.0 and it works.

**Comment by DanielVanNoord** [comment]
I just ran a quick test and the current nuget package (https://www.nuget.org/packages/Core.System.Windows.Forms/1.0.0-alpha4) seems to work correctly when used in a .Net 8 on Ubuntu as long as you use version 6 of System.Drawing.Common from nuget. The nuget package is set to pull that automatically. Did you try and run it and run into an error?

**Comment by sancheolz** [comment]
@davidbitterlich  why can't you use version 6.0 of System.Drawing.Common as this project does? If you set EnableUnixSupport to true in runtimeconfig.json file you will able to use Drawing on Mac and Linux. What is API of Drawing from mono work better than API from Drawing.Common? With this project and System.Drawing.Common our project able to run on Linux with net8. Porting Mono's Drawing is not so easy, I've tried to do it, but found a lot of problems.

**Comment by davidbitterlich** [comment]
The thing is that we are currently stuck with this particular version of Drawing. What are the future plans of this System.Windows.Forms port? Are you interested in maintaining it for future dotnet releases? If so, it might become necessary to circumvent compatibility issues which will be caused by the Microsoft implementation one day...

**Comment by sancheolz** [comment]
The mono project is currently not supported. The level of development of its System.Drawing, in my opinion, is the same as System.Drawing.Common. Another problem is that Linux distributions are starting to migrate from X11 to Wayland, and our WinForms is written for X11, and if I'm not mistaken, then libgdiplus. Now the mono project has been forked by an enthusiast from wine-mono. It is difficult to say whether he has the strength to solve the above problems. If Drawing is needed only for image processing without binding to Winforms, then it is worth looking at ImagSharp, SkiaSharp, IronSoftware.Drawing.

**Comment by mfeemster** [comment]
In another issue I posted here recently: https://github.com/DanielVanNoord/System.Windows.Forms/issues/11

It appears that the System.Drawing you are using is lacking in at least that area, and perhaps more.

Since we cannot change the System.Drawing.Common library that Microsoft provides, we'll probably need a custom build of it that uses some of Mono's code.

**Comment by sancheolz** [comment]
We also caught the difference in implementation in #5 . It looks like Winforms from mono is better integrated with Drawing from it. I'm not against creating a Drawing fork. This will allow us to use more original code from mono WinForms. But I'm a contributor, not an author.
